# fly.toml app configuration file generated for navi-holy-fog-1609 on 2025-07-06T18:04:19+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'navi-holy-fog-1609'
primary_region = 'lhr'

[build]

[processes]
  web = "python run_web.py"
  telegram = "python run_telegram.py"

[http_service]
  internal_port = 4999
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['web']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
